In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

import jupyter_dash
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from datetime import datetime as dt, date, time, timedelta

# https://github.com/d3/d3-3.x-api-reference/blob/master/Time-Formatting.md#format

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

# Study Timelines

### Unused

In [3]:
# df = pd.DataFrame([
#     dict(Study="Experiment 1", Start='2020-01-01', Finish='2023-03-11'),
#     dict(Study="Experiment 2", Start='2022-11-13', Finish='2023-01-22'),
# ])
# df

In [4]:
# fig = px.timeline(df, x_start="Start", x_end="Finish", y="Study", color="Study", height=300)
# fig.update_yaxes(autorange="reversed")
# fig.show(renderer="browser")

In [5]:
# fig.write_image("data/images/study-timeline1.png")

### Experiment 1 vs Experiment 2

In [6]:
# df = pd.DataFrame([
#     dict(Study="Experiment 1", Start='2020-01-01', Finish='2023-03-11', Phase="Experiment 1"),
#     dict(Study="Experiment 2", Start='2022-11-13', Finish='2022-11-26', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2022-11-27', Finish='2022-12-10', Phase="Experiment 2 A"),
#     dict(Study="Experiment 2", Start='2022-12-11', Finish='2022-12-24', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2022-12-25', Finish='2023-01-07', Phase="Experiment 2 A"),
#     dict(Study="Experiment 2", Start='2023-01-08', Finish='2023-01-22', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2023-01-23', Finish='2023-02-05', Phase="Experiment 2 A"),
# ])
# df

In [7]:
# fig = px.timeline(df, x_start="Start", x_end="Finish", y="Study", color="Phase", 
#                   title="Timeline of Longitudinal Studies", height=300)
# fig.update_yaxes()
# fig.update_xaxes(
#     dtick='M3',)
# fig.show(renderer="browser")

In [8]:
# fig.write_image("data/images/study-timeline2.png", width=1000)

### Experiment 2 Closeup

In [9]:
# df = pd.DataFrame([
#     dict(Study="Experiment 2", Start='2022-11-13', Finish='2022-11-26', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2022-11-27', Finish='2022-12-10', Phase="Experiment 2 A"),
#     dict(Study="Experiment 2", Start='2022-12-11', Finish='2022-12-24', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2022-12-25', Finish='2023-01-07', Phase="Experiment 2 A"),
#     dict(Study="Experiment 2", Start='2023-01-08', Finish='2023-01-22', Phase="Experiment 2 B"),
#     dict(Study="Experiment 2", Start='2023-01-23', Finish='2023-02-05', Phase="Experiment 2 A"),
# ])
# df

In [10]:
# fig = px.timeline(df, x_start="Start", x_end="Finish", y="Study", color="Phase", 
#                   title="Timeline of Experiment 2: Biweekly Crossover Phase Design Study",
#                   color_discrete_map={
#                                       'Experiment 2 B': '#EF553B',
#                                       'Experiment 2 A': '#00CC96'},
#                   height=300)
# fig.update_yaxes()
# fig.update_xaxes(
#     dtick=86400000*7,
#     tickformat="%x")
# fig.show(renderer="browser")

In [11]:
# fig.write_image("data/images/study-timeline3.png", width=1000)

In [12]:
# px.colors.qualitative.swatches()

### MWU timeline

In [10]:
# df = pd.DataFrame([
#     dict(Groups="Groups", Start='2020-01-01', Finish='2022-11-12', Group="Pre-Experiment 2"),
#     dict(Groups="Groups", Start='2022-11-13', Finish='2023-03-10', Group="Experiment 2 and After"),
# ])
# df

   Groups       Start      Finish                   Group
0  Groups  2020-01-01  2022-11-12        Pre-Experiment 2
1  Groups  2022-11-13  2023-03-10  Experiment 2 and After

In [11]:
# fig = px.timeline(df, x_start="Start", x_end="Finish", y="Groups", color="Group", 
#                   title="Timeline of Mann-Whitney-U Groups", height=300)
# fig.update_yaxes()
# fig.update_xaxes(
#     dtick='M3',)
# fig.show(renderer="browser")

In [12]:
# fig.write_image("data/images/MWU-group-timeline.png", width=1000)

# Time head/tail and stats tables

In [13]:
report = 'data/time_2020-present.csv'
df = pd.read_csv(report)
df

,Group,Activity type,Duration,From,To,Comment
0,NaN,Toilet,0:17:55,2023-03-12 23:56:28,2023-03-13 0:14:23,NaN
1,NaN,Studying,0:19:21,2023-03-12 23:35:58,2023-03-12 23:55:19,NaN
2,NaN,Eating,0:11:26,2023-03-12 23:14:19,2023-03-12 23:25:45,NaN
3,NaN,Toilet,0:02:06,2023-03-12 22:38:49,2023-03-12 22:40:55,NaN
4,NaN,Studying,1:00:01,2023-03-12 21:35:43,2023-03-12 22:35:44,NaN
...,...,...,...,...,...,...
30157,NaN,Toilet,0:01:35,2019-12-31 1:27:22,2019-12-31 1:28:57,NaN
30158,NaN,Grooming,0:05:42,2019-12-31 1:21:40,2019-12-31 1:27:22,NaN
30159,Computer,Internet,0:08:01,2019-12-31 1:13:03,2019-12-31 1:21:04,NaN
30160,Personal,Masturbation,0:06:19,2019-12-31 1:06:36,2019-12-31 1:12:55,NaN
30161,Computer,Internet,1:42:24,2019-12-30 23:24:10,2019-12-31 1:06:34,NaN

In [14]:
df_tail = df.head(5)
df_head_tail = df_tail.append(df[:-5].tail(5))
df_head_tail

/tmp/ipykernel_88463/1874526212.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_head_tail = df_tail.append(df[:-5].tail(5))

,Group,Activity type,Duration,From,To,Comment
0,NaN,Toilet,0:17:55,2023-03-12 23:56:28,2023-03-13 0:14:23,NaN
1,NaN,Studying,0:19:21,2023-03-12 23:35:58,2023-03-12 23:55:19,NaN
2,NaN,Eating,0:11:26,2023-03-12 23:14:19,2023-03-12 23:25:45,NaN
3,NaN,Toilet,0:02:06,2023-03-12 22:38:49,2023-03-12 22:40:55,NaN
4,NaN,Studying,1:00:01,2023-03-12 21:35:43,2023-03-12 22:35:44,NaN
30152,Computer,Internet,3:08:53,2019-12-31 8:40:09,2019-12-31 11:49:02,NaN
30153,Housework,Cooking,0:13:30,2019-12-31 8:20:10,2019-12-31 8:33:40,NaN
30154,Computer,Internet,2:26:52,2019-12-31 5:52:35,2019-12-31 8:19:27,NaN
30155,NaN,Toilet,0:01:21,2019-12-31 5:48:13,2019-12-31 5:49:34,NaN
30156,NaN,Sleeping,4:17:50,2019-12-31 1:29:56,2019-12-31 5:47:46,NaN

In [15]:
# df_head_tail.to_csv('data/time_df_head_tail.csv', index=None, encoding='utf-8')

In [16]:
df = pd.read_csv('data/df2_with_durations.csv')
df

,Date,Step Count,Resting Heart Rate,Number of Floors,Timestamp,Mood,Pain,Tired,Sick,Anxiousness,...,concert_event_durations,concert_event_durations_seconds_7_day_rolling_mean,biking_durations_seconds,biking_counts,biking_durations,biking_durations_seconds_7_day_rolling_mean,dancing_durations_seconds,dancing_counts,dancing_durations,dancing_durations_seconds_7_day_rolling_mean
0,2020-01-01,1041,56.0,0,2020-01-01 09:05:41,1.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1,2020-01-02,321,58.0,0,2020-01-02 23:59:59,1.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
2,2020-01-03,1659,57.0,1,2020-01-03 23:47:21,2.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
3,2020-01-04,8407,58.0,8,2020-01-04 14:35:28,1.0,2.0,1.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
4,2020-01-05,4520,57.0,2,2020-01-05 19:08:20,2.0,2.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1161,2023-03-07,4960,55.0,8,2023-03-07 18:46:09,2.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1162,2023-03-08,358,53.0,0,2023-03-08 18:42:18,2.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1163,2023-03-09,749,54.0,0,2023-03-09 19:14:30,2.0,0.0,1.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1164,2023-03-10,3203,53.0,1,2023-03-10 19:00:52,2.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1165,2023-03-11,8643,55.0,5,2023-03-11 18:55:42,2.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0

In [24]:
columns = [#'Date', 
           'Timestamp',
           'Step Count',
           'Resting Heart Rate',
           'Number of Floors',
           
           'Mood', 
           'Pain', 
           'Tired',
           'Sick',
           'Anxiousness', 
           'Depressed', 
           'Suicidal',
           'Self-Harm',
           'Thoughts of Death', 
           'Repetitive Thoughts',
           'Thoughts of Worthlessness', 
           'Thoughts of Hopelessness',
           'Brain Sludge', 
           'Sluggish', 
           'Restless', 
           'Existential Crisis', 
           'Weird',
           'Loss of Interest', 
           'Self Isolation', 
           'Paranoia',
           'Elevated', 
           'Irritable/Angry',
           'Loneliness', 
           'Libido', 
           'Weight', 
           
           'Month',
           'Day',
           'Weekday',
           'Week']

In [25]:
df_shifted = [i for i in df.columns if i.endswith('shifted')]
df_shifted

[]

In [26]:
df = df[df.columns[~df.columns.isin(columns)]]
# df = df[df.columns[~df.columns.isin(df_shifted)]]
df

,Date,sleeping_durations_seconds,sleeping_counts,sleeping_durations,sleeping_durations_seconds_7_day_rolling_mean,internet_durations_seconds,internet_counts,internet_durations,internet_durations_seconds_7_day_rolling_mean,working_durations_seconds,...,concert_event_durations,concert_event_durations_seconds_7_day_rolling_mean,biking_durations_seconds,biking_counts,biking_durations,biking_durations_seconds_7_day_rolling_mean,dancing_durations_seconds,dancing_counts,dancing_durations,dancing_durations_seconds_7_day_rolling_mean
0,2020-01-01,26261.0,2.0,07:17:41,0.0,37528.0,7.0,10:25:28,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1,2020-01-02,55405.0,2.0,15:23:25,0.0,29718.0,3.0,08:15:18,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
2,2020-01-03,41466.0,2.0,11:31:06,0.0,35031.0,4.0,09:43:51,0.0,2241.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
3,2020-01-04,15501.0,1.0,04:18:21,0.0,3816.0,2.0,01:03:36,0.0,45764.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
4,2020-01-05,16834.0,1.0,04:40:34,0.0,36763.0,5.0,10:12:43,26571.0,28069.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1161,2023-03-07,12784.0,1.0,03:33:04,27653.0,47948.0,5.0,13:19:08,28972.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1162,2023-03-08,61429.0,2.0,17:03:49,32995.0,20725.0,4.0,05:45:25,24284.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1163,2023-03-09,21987.0,1.0,06:06:27,31660.0,62929.0,6.0,17:28:49,26067.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1164,2023-03-10,59984.0,1.0,16:39:44,32695.0,8750.0,4.0,02:25:50,26585.0,16157.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1165,2023-03-11,21918.0,1.0,06:05:18,32215.0,12047.0,3.0,03:20:47,26575.0,43827.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0

In [31]:
df_tail = df.head(5)
df_head_tail = df_tail.append(df[:-5].tail(5))
df_head_tail

/tmp/ipykernel_88463/1874526212.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_head_tail = df_tail.append(df[:-5].tail(5))

,Date,sleeping_durations_seconds,sleeping_counts,sleeping_durations,sleeping_durations_seconds_7_day_rolling_mean,internet_durations_seconds,internet_counts,internet_durations,internet_durations_seconds_7_day_rolling_mean,working_durations_seconds,...,concert_event_durations,concert_event_durations_seconds_7_day_rolling_mean,biking_durations_seconds,biking_counts,biking_durations,biking_durations_seconds_7_day_rolling_mean,dancing_durations_seconds,dancing_counts,dancing_durations,dancing_durations_seconds_7_day_rolling_mean
0,2020-01-01,26261.0,2.0,07:17:41,0.0,37528.0,7.0,10:25:28,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1,2020-01-02,55405.0,2.0,15:23:25,0.0,29718.0,3.0,08:15:18,0.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
2,2020-01-03,41466.0,2.0,11:31:06,0.0,35031.0,4.0,09:43:51,0.0,2241.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
3,2020-01-04,15501.0,1.0,04:18:21,0.0,3816.0,2.0,01:03:36,0.0,45764.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
4,2020-01-05,16834.0,1.0,04:40:34,0.0,36763.0,5.0,10:12:43,26571.0,28069.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1156,2023-03-02,31331.0,1.0,08:42:11,26734.0,50453.0,5.0,14:00:53,30353.0,0.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1157,2023-03-03,52740.0,2.0,14:39:00,28965.0,5121.0,2.0,01:25:21,27428.0,15847.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1158,2023-03-04,25274.0,1.0,07:01:14,29764.0,12120.0,4.0,03:22:00,26819.0,44353.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1159,2023-03-05,22667.0,1.0,06:17:47,30249.0,14425.0,3.0,04:00:25,26922.0,44809.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0
1160,2023-03-06,24738.0,1.0,06:52:18,30649.0,19198.0,4.0,05:19:58,25045.0,28145.0,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0

In [33]:
# df_head_tail.to_csv('data/time_df_head_tail_full.csv', index=None, encoding='utf-8')

In [27]:
df_describe = df.describe()
df_describe

,sleeping_durations_seconds,sleeping_counts,sleeping_durations_seconds_7_day_rolling_mean,internet_durations_seconds,internet_counts,internet_durations_seconds_7_day_rolling_mean,working_durations_seconds,working_counts,working_durations_seconds_7_day_rolling_mean,games_durations_seconds,...,data_analysis_durations_seconds_7_day_rolling_mean,concert_event_durations_seconds,concert_event_counts,concert_event_durations_seconds_7_day_rolling_mean,biking_durations_seconds,biking_counts,biking_durations_seconds_7_day_rolling_mean,dancing_durations_seconds,dancing_counts,dancing_durations_seconds_7_day_rolling_mean
count,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.00000,1166.000000,1166.000000,1166.000000,...,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.0,1166.000000,1166.000000,1166.0
mean,29557.022298,1.388508,29405.391938,20020.291595,3.934820,19925.454545,19839.42024,0.925386,19748.409091,3250.199828,...,14.256432,12.843911,0.001715,1.834477,5.704117,0.000858,0.0,0.813036,0.000858,0.0
std,9787.187219,0.570374,3130.126646,12155.456221,1.835989,6217.341710,17858.84017,0.792946,5881.710501,7702.826734,...,94.317182,371.124249,0.041398,53.008713,194.777000,0.029285,0.0,27.762531,0.029285,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
25%,22991.250000,1.000000,27970.750000,10549.000000,3.000000,15313.750000,0.00000,0.000000,17240.250000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
50%,27718.000000,1.000000,29580.000000,18063.500000,4.000000,19465.500000,16587.50000,1.000000,19167.500000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
75%,35983.250000,2.000000,31168.750000,27679.500000,5.000000,24296.750000,32404.00000,2.000000,23290.500000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
max,62138.000000,4.000000,36714.000000,62929.000000,12.000000,37602.000000,72596.00000,3.000000,38024.000000,54760.000000,...,1010.000000,12413.000000,1.000000,1773.000000,6651.000000,1.000000,0.0,948.000000,1.000000,0.0

In [28]:
# df_describe.to_csv('data/time_df_describe.csv', index=None, encoding='utf-8')