In [204]:
# Dependencies
import numpy as np, string, re, pytz
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [205]:
books = pd.read_csv("data/books.csv")

In [206]:
books

,id,rating,votes,spoiler_flag,spoilers_state,shelves,recommended_for,recommended_by,started_at,read_at,...,url,link,owned,author,title,title_without_series,image_url,num_page,publication_year,average_rating
0,3605288048,0,0,False,none,to-read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/3605288048,https://www.goodreads.com/review/show/3605288048,0,Alastair Reynolds,"Blue Remembered Earth (Poseidon's Children, #1)",Blue Remembered Earth,https://i.gr-assets.com/images/S/compressed.ph...,512.0,2012.0,3.88
1,3582617192,0,0,False,none,to-read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/3582617192,https://www.goodreads.com/review/show/3582617192,0,Adrian Raine,The Anatomy of Violence: The Biological Roots ...,The Anatomy of Violence: The Biological Roots ...,https://i.gr-assets.com/images/S/compressed.ph...,528.0,2013.0,3.98
2,3567184632,0,0,False,none,to-read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/3567184632,https://www.goodreads.com/review/show/3567184632,0,Annie Jacobsen,The Pentagon's Brain: An Uncensored History of...,The Pentagon's Brain: An Uncensored History of...,https://i.gr-assets.com/images/S/compressed.ph...,560.0,2015.0,3.90
3,3553776237,0,0,False,none,to-read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/3553776237,https://www.goodreads.com/review/show/3553776237,0,Tanya Huff,"Valor's Choice (Confederation, #1)",Valor's Choice,https://s.gr-assets.com/assets/nophoto/book/11...,416.0,2000.0,3.98
4,3553774452,0,0,False,none,to-read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/3553774452,https://www.goodreads.com/review/show/3553774452,0,Alan Dean Foster,"A Call to Arms (The Damned, #1)",A Call to Arms,https://i.gr-assets.com/images/S/compressed.ph...,341.0,1994.0,3.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,984393234,4,0,False,none,read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/984393234,https://www.goodreads.com/review/show/984393234,1,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",The Hunger Games,https://i.gr-assets.com/images/S/compressed.ph...,374.0,2008.0,4.33
991,984393213,5,0,False,none,read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/984393213,https://www.goodreads.com/review/show/984393213,0,Ray Bradbury,Fahrenheit 451,Fahrenheit 451,https://i.gr-assets.com/images/S/compressed.ph...,227.0,2013.0,3.99
992,984393072,5,0,False,none,read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/984393072,https://www.goodreads.com/review/show/984393072,0,Isaac Asimov,Foundation and Empire (Foundation #2),Foundation and Empire,https://s.gr-assets.com/assets/nophoto/book/11...,256.0,2004.0,4.22
993,984392984,5,0,False,none,read,NaN,NaN,NaN,NaN,...,https://www.goodreads.com/review/show/984392984,https://www.goodreads.com/review/show/984392984,1,Arthur C. Clarke,"Rendezvous with Rama (Rama, #1)",Rendezvous with Rama,https://i.gr-assets.com/images/S/compressed.ph...,243.0,2000.0,4.10
994,984392665,5,0,False,none,read,NaN,NaN,NaN,2014-01-01,...,https://www.goodreads.com/review/show/984392665,https://www.goodreads.com/review/show/984392665,1,Douglas Adams,The Hitchhiker's Guide to the Galaxy (Hitchhik...,The Hitchhiker's Guide to the Galaxy,https://i.gr-assets.com/images/S/compressed.ph...,216.0,2005.0,4.22

In [207]:
books.shape

(995, 25)

In [208]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    995 non-null    int64
 1   rating                995 non-null    int64
 2   votes                 995 non-null    int64
 3   spoiler_flag          995 non-null    bool
 4   spoilers_state        995 non-null    object
 5   shelves               995 non-null    object
 6   recommended_for       0 non-null      float64
 7   recommended_by        0 non-null      float64
 8   started_at            48 non-null     object
 9   read_at               105 non-null    object
 10  date_added            995 non-null    object
 11  date_updated          995 non-null    object
 12  read_count            995 non-null    int64
 13  body                  0 non-null      float64
 14  comments_count        995 non-null    int64
 15  url                   995 non-null    object
 16  link                  995 non-null    object
 17  owned                 995 non-null    int64
 18  author                995 non-null    object
 19  title                 995 non-null    object
 20  title_without_series  995 non-null    object
 21  image_url             995 non-null    object
 22  num_page              938 non-null    float64
 23  publication_year      913 non-null    float64
 24  average_rating        995 non-null    float64
dtypes: bool(1), float64(6), int64(6), object(12)
memory usage: 187.7+ KB

In [209]:
books['started_at'] = pd.to_datetime(books['started_at'])
books['read_at'] = pd.to_datetime(books['read_at'])
books['date_added'] = pd.to_datetime(books['date_added'])
books['date_updated'] = pd.to_datetime(books['date_updated'])

In [210]:
books['rating'] = pd.to_numeric(books["rating"])
books['average_rating'] = pd.to_numeric(books["average_rating"])
books['read_count'] = pd.to_numeric(books["read_count"])
books["num_page"] = pd.to_numeric(books["num_page"])

In [211]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    995 non-null    int64
 1   rating                995 non-null    int64
 2   votes                 995 non-null    int64
 3   spoiler_flag          995 non-null    bool
 4   spoilers_state        995 non-null    object
 5   shelves               995 non-null    object
 6   recommended_for       0 non-null      float64
 7   recommended_by        0 non-null      float64
 8   started_at            48 non-null     datetime64[ns]
 9   read_at               105 non-null    datetime64[ns]
 10  date_added            995 non-null    datetime64[ns]
 11  date_updated          995 non-null    datetime64[ns]
 12  read_count            995 non-null    int64
 13  body                  0 non-null      float64
 14  comments_count        995 non-null    int64
 15  url                   995 non-null    object
 16  link                  995 non-null    object
 17  owned                 995 non-null    int64
 18  author                995 non-null    object
 19  title                 995 non-null    object
 20  title_without_series  995 non-null    object
 21  image_url             995 non-null    object
 22  num_page              938 non-null    float64
 23  publication_year      913 non-null    float64
 24  average_rating        995 non-null    float64
dtypes: bool(1), datetime64[ns](4), float64(6), int64(6), object(8)
memory usage: 187.7+ KB

In [212]:
books['year_read'] = pd.DatetimeIndex(books.read_at).year
books['month_read'] = pd.DatetimeIndex(books.read_at).month
books['day_read'] = pd.DatetimeIndex(books.read_at).day
books['weekday_read'] = pd.DatetimeIndex(books.read_at).weekday

In [213]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    995 non-null    int64
 1   rating                995 non-null    int64
 2   votes                 995 non-null    int64
 3   spoiler_flag          995 non-null    bool
 4   spoilers_state        995 non-null    object
 5   shelves               995 non-null    object
 6   recommended_for       0 non-null      float64
 7   recommended_by        0 non-null      float64
 8   started_at            48 non-null     datetime64[ns]
 9   read_at               105 non-null    datetime64[ns]
 10  date_added            995 non-null    datetime64[ns]
 11  date_updated          995 non-null    datetime64[ns]
 12  read_count            995 non-null    int64
 13  body                  0 non-null      float64
 14  comments_count        995 non-null    int64
 15  url                   995 non-null    object
 16  link                  995 non-null    object
 17  owned                 995 non-null    int64
 18  author                995 non-null    object
 19  title                 995 non-null    object
 20  title_without_series  995 non-null    object
 21  image_url             995 non-null    object
 22  num_page              938 non-null    float64
 23  publication_year      913 non-null    float64
 24  average_rating        995 non-null    float64
 25  year_read             105 non-null    float64
 26  month_read            105 non-null    float64
 27  day_read              105 non-null    float64
 28  weekday_read          105 non-null    float64
dtypes: bool(1), datetime64[ns](4), float64(10), int64(6), object(8)
memory usage: 218.8+ KB

In [163]:
"""
from IPython.display import display
with pd.option_context('display.max_rows', 1000):
    display(books.year_read)
"""

In [164]:
books_yearly = pd.DataFrame()
books_yearly['Yearly Read'] = []
books_yearly['Yearly Read'] = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
#books_yearly.at[0, 'Yearly Read'] = books_yearly[books_yearly.year == 2014][['read_at']].sum()

In [229]:
books_monthly = pd.DataFrame()
books_monthly['Monthly Read'] = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]

In [230]:
books_monthly

    Monthly Read
0            0.0
1            1.0
2            2.0
3            3.0
4            4.0
5            5.0
6            6.0
7            7.0
8            8.0
9            9.0
10          10.0
11          11.0

In [231]:
books_monthly.at[0, 'Monthly Read'] = books[books.month_read == 2015][['read_at']].mean()

IndexError: single positional indexer is out-of-bounds

In [ ]:
books_day = pd.DataFrame()

In [ ]:
books_weekday = pd.DataFrame()

In [143]:
# Book Reading Summary
print('====== Goodreads Summary ======')
print('{:,} total books in your Goodreads account'.format(len(books)))
print('{:,} total number of books read'.format(len(books[books['shelves'] == 'read'])))
print('{:,} books currently reading'.format(len(books[books['shelves'] == 'currently-reading'])))
print('{:,} books still to read'.format(len(books[books['shelves'] == 'to-read'])))

====== Goodreads Summary ======
995 total books in your Goodreads account
201 total number of books read
0 books currently reading
790 books still to read